### ISSUE TITLE
wellness results ?! (3h)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#21] opened 2019-08-19 07:12 UTC
this is actually a template... like instagram stories or amp stories https://eager-chandrasekhar-f0dbb1.netlify.com/

whenever a user clicks on those tiny square images, it should open this story template which should exist as a standalone page. We want to use these story pages on social media.

**Comment by mort3za** [comment] 2019-09-27 08:19
duplicate of #37

**Closed by mort3za** 2019-09-27 08:19 UTC
